meta_product_name: "The Digital Compass"
meta_title: "The Digital Compass | A 'GPS' for your career in Tech!"
meta_description: "Thinking about changing to a career in Tech? The Digital Compass is your automated career coach. Get recommendations. Future-proof your career. Start today!"
meta_image: "cover.png" # should exist in `app/assets/images/`
